# Generated by Django 5.2.4 on 2025-07-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('mystery', 'Mystery & Thriller'), ('nonfiction', 'Non-Fiction'), ('romance', 'Romance'), ('scifi', 'Sci‑Fi & Fantasy'), ('education', 'Educational & Academic'), ('children', 'Children & Young Adult'), ('tech', 'Tech & Programming')], max_length=50)),
                ('published_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
